"""rename address

Revision ID: eb48b7e54b85
Revises: 8c7df1beb014
Create Date: 2024-02-19 17:20:02.853905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb48b7e54b85'
down_revision = '8c7df1beb014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", 'location', new_column_name='address')
    # ### end Alembic commands ###
